
# Setup
title:               Techno Elektro
email:               technoelektro.pl@gmail.com
tagline:             Smart Home Services
url:                 "https://magnetofield.github.io/techno-elektro-1/" # insert your site's URL
baseurl:             "https://magnetofield.github.io/techno-elektro-1/"

# About/contact
author: # you can edit these to be your personal details
  name:              Techno Elektro
  url:               https://twitter.com/technoelektro1
  email:             technoelektro.pl@gmail.com

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-132680216-1
google_tag_manager:
# Bing services
bing_verification:

# Social
github_username: thundergolfer
twitter_username: technoelektro1
instagram_username: kevin/
facebook: TechnoElektroPl/
linkedin_username: xiaoying
dribbble_username: Xiaoying

# Custom vars
version:             1.0.1
github:
  repo:              https://github.com/kevit/devaid-jekyll-theme

# Gems - Dependencies for this theme
gems:
  # None currently

# Build settings
markdown:     kramdown
permalink:    pretty

widgets:
  - title: O nas
    url: about
    archor: true
  - title: Oferta
    url: features
    archor: true
  - title: Smart Home
    url: docs
    archor: true
  - title: Kontakt
    url: contact
    archor: true
#  - title: calendar
#    url: calendar
#  - title: Blog
#    url: blog
#  - title: Page
#    url: page
#  - title: Recycling
#    url: recycling
